let catalog=[],cart=JSON.parse(localStorage.getItem('novaCart')||'[]'),wish=JSON.parse(localStorage.getItem('novaWish')||'[]');
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
async function init(){catalog=await (await fetch('data/catalog.json')).json();render();counts();const q=new URLSearchParams(location.search).get('q');if(q&&document.querySelector('#catalog-search')){document.querySelector('#catalog-search').value=q;filterProducts()}}
function render(list=catalog){const el=document.querySelector('#product-grid');if(!el)return;el.innerHTML=list.map((p,i)=>`<article class="product"><div class="pimg"><span class="badge">${i<3?'Featured':'Popular'}</span><button class="heart" onclick="toggleWish('${p.slug}',this)">${wish.includes(p.slug)?'♥':'♡'}</button><img src="assets/images/products/${p.image}" alt="${p.name}"></div><div class="pbody"><span class="category">${p.category}</span><h3>${p.name}</h3><div class="rating">★★★★★ <span class="muted">(${p.reviews})</span></div><div class="price">${money(p.price)}</div><p>${p.description}</p><a class="btn" href="products/${p.slug}.html">View product</a></div></article>`).join('')}
function filterProducts(){let q=(document.querySelector('#catalog-search')?.value||'').toLowerCase(),c=document.querySelector('#catalog-category')?.value||new URLSearchParams(location.search).get('category')||'',s=document.querySelector('#catalog-sort')?.value||'';let a=catalog.filter(p=>(!q||(p.name+p.category+p.description).toLowerCase().includes(q))&&(!c||p.category===c));if(s==='low')a.sort((x,y)=>x.price-y.price);if(s==='high')a.sort((x,y)=>y.price-x.price);if(s==='rating')a.sort((x,y)=>y.rating-x.rating);render(a)}
function toggleWish(slug,b){wish=wish.includes(slug)?wish.filter(x=>x!==slug):[...wish,slug];localStorage.setItem('novaWish',JSON.stringify(wish));if(b)b.textContent=wish.includes(slug)?'♥':'♡';counts();toast(wish.includes(slug)?'Added to wishlist':'Removed from wishlist')}
function addToCart(slug){let x=cart.find(a=>a.slug===slug);x?x.qty++:cart.push({slug,qty:1});localStorage.setItem('novaCart',JSON.stringify(cart));counts();toast('Added to cart')}
function counts(){document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cart.reduce((a,b)=>a+b.qty,0));document.querySelectorAll('[data-wish-count]').forEach(e=>e.textContent=wish.length)}
function openCart(){renderCart();document.querySelector('.drawer').classList.add('open');document.querySelector('.overlay').classList.add('show')}
function closeCart(){document.querySelector('.drawer').classList.remove('open');document.querySelector('.overlay').classList.remove('show')}
function renderCart(){let e=document.querySelector('[data-cart]');if(!e)return;if(!cart.length){e.innerHTML='<p class="muted">Your cart is empty.</p>';return}let total=0;e.innerHTML=cart.map(x=>{let p=catalog.find(a=>a.slug===x.slug);total+=p.price*x.qty;return `<div class="cart-row"><img src="assets/images/products/${p.image}" alt=""><div><b>${p.name}</b><div>${money(p.price)} × ${x.qty}</div></div><button class="btn" onclick="removeCart('${p.slug}')">×</button></div>`}).join('')+`<h3>Total ${money(total)}</h3><button class="btn primary" onclick="toast('Demo checkout ready')">Checkout</button>`}
function removeCart(slug){cart=cart.filter(x=>x.slug!==slug);localStorage.setItem('novaCart',JSON.stringify(cart));counts();renderCart()}
function toast(m){let e=document.querySelector('.toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2000)}
document.addEventListener('DOMContentLoaded',()=>{init();let s=document.querySelector('#site-search');if(s)s.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='shop.html?q='+encodeURIComponent(s.value)})});
